config/routes.rb
Rails.application.routes.draw do
  concern :collaboratable do
    resources :collaborations, only: [:create, :destroy, :index, :show]
  end

  concern :activities do
    resources :activities, only: [:index]
  end

  get 'edam/terms' => 'edam#terms'
  get 'edam/topics' => 'edam#topics'
  get 'edam/operations' => 'edam#operations'

  if TeSS::Config.feature['workflows'] == true
    resources :workflows
  end

  get 'about' => 'about#tess', as: 'about'
  get 'about/registering' => 'about#registering', as: 'registering_resources'
  get 'about/developers' => 'about#developers', as: 'developers'
  get 'about/us' => 'about#us', as: 'us'

  get 'privacy' => 'static#privacy', as: 'privacy'

  post 'materials/check_exists' => 'materials#check_exists'
  post 'events/check_exists' => 'events#check_exists'
  post 'content_providers/check_exists' => 'content_providers#check_exists'
  post 'sources/check_exists' => 'sources#check_exists'

  if (ActiveRecord::Base.connection rescue false)
    devise_for :users, :controllers => {
      :registrations => 'tess_devise/registrations',
      :invitations => 'tess_devise/invitations',
      :omniauth_callbacks => 'callbacks'
    }
  end

  patch 'users/:id/change_token' => 'users#change_token', as: 'change_token'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'static#home'

  get 'static/home'

  resources :users do
    resource :ban, only: [:create, :new, :destroy]
  end

  resources :sources, concerns: :activities

  if TeSS::Config.feature['trainers'] == true
    resources :trainers, only: [:show, :index]
  end

  if TeSS::Config.feature['nodes'] == true
    resources :nodes, concerns: :activities
  end

  if TeSS::Config.feature['events'] == true
    resources :events, concerns: :activities do
      collection do
        get 'count'
      end
      member do
        get 'redirect'
        post 'add_term'
        post 'add_data'
        post 'reject_term'
        post 'reject_data'
        get 'report'
        patch 'report', to: 'events#update_report'
        get 'clone', to: 'events#clone'
      end
    end
  end

  if TeSS::Config.feature['packages'] == true
    resources :packages, concerns: :activities
  end

  if TeSS::Config.feature['workflows'] == true
    resources :workflows, concerns: [:collaboratable, :activities] do
      member do
        get 'fork'
        get 'embed'
      end
    end
  end

  if TeSS::Config.feature['providers'] == true
    resources :content_providers, concerns: :activities
  end

  if TeSS::Config.feature['materials'] == true
    resources :materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['e-learnings'] == true
    resources :elearning_materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['invitation'] == true
    get 'invitees' => 'users#invitees'
  end

  resources :subscriptions, only: [:show, :index, :create, :destroy] do
    member do
      get 'unsubscribe'
    end
  end

  get 'stars' => 'stars#index'
  post 'stars' => 'stars#create'
  delete 'stars' => 'stars#destroy'

  post 'materials/:id/update_packages' => 'materials#update_packages'
  post 'events/:id/update_packages' => 'events#update_packages'

  get 'search' => 'search#index'
  get 'test_url' => 'application#test_url'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "application#handle_error", :status_code => code
  end

  get 'curate/topic_suggestions' => 'curator#topic_suggestions'
  get 'curate/users' => 'curator#users'
  get 'curate' => 'curator#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'resolve/:prefix:type:id' => 'resolution#resolve', constraints: { prefix: /(.+\:)?/, type: /[a-zA-Z]/, id: /\d+/ }

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  CHECK_WINDOW = 1.hour # Window to add to subscription period to avoid synchronization issues with cronjob to process
                        # subscriptions.
                        # e.g. A window of 1 hour will make a daily subscription "due" 23 hours after it was last checked.

  FREQUENCY = [
      { key: :daily, id: 1, period: 1.day, title: '24 hours' }.with_indifferent_access,
      { key: :weekly, id: 2, period: 1.week, title: '1 week' }.with_indifferent_access,
      { key: :monthly, id: 3, period: 1.month, title: '1 month' }.with_indifferent_access
  ].freeze

  validates :frequency, presence: true, inclusion: { in: FREQUENCY.map { |f| f[:key] } }
  validates :subscribable_type, presence: true
  validate :valid_subscribable_type
  belongs_to :user

  before_create :set_last_checked_at

  def frequency
    FREQUENCY.detect { |f| f[:id] == super }.try(:[], :key)
  end

  def frequency= freq
    super(FREQUENCY.detect { |f| f[:key] == freq.to_sym }.try(:[], :id))
  end

  def unsubscribe_code
    unsubscribe_verifier.generate(self.id).split('--').last
  end

  def valid_unsubscribe_code?(code)
    unsubscribe_verifier.verify("#{Base64.encode64(Marshal.dump(self.id)).chomp}--#{code}") == self.id
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    false
  end

  def digest
    type = subscribable_type.constantize

    type.search_and_filter(user, query, facets_with_max_age, per_page: 15).results
  end

  def facets_with_max_age
    facets.merge(max_age: max_age).with_indifferent_access
  end

  def period
    FREQUENCY.detect { |f| f[:id] == self[:frequency] }[:period]
  end

  def due?
    last_checked_at < (period - CHECK_WINDOW).ago
  end

  def check
    update_attribute(:last_checked_at, Time.now)
  end

  def process
    r = digest

    if r.any?
      SubscriptionMailer.digest(self, r).deliver_now
      self.last_sent_at = Time.now # This will be saved when `check` is called below
    end
    check
  end

  def self.due
    clause = FREQUENCY.map do |freq|
      "(frequency = '#{freq[:id]}' AND last_checked_at < '#{freq[:period].ago}')"
    end.join(' OR ')

    where(clause)
  end

  def reset_due
    update_attribute(:last_checked_at, Time.now - (2 * period))
  end

  private

  def max_age
    FREQUENCY.detect { |f| f[:id] == self[:frequency] }[:title]
  end

  def valid_subscribable_type
    begin
      type = self.subscribable_type.constantize
    rescue NameError
      type = nil
    end

    unless type && type.respond_to?(:search_and_filter)
      errors.add(:subscribable_type, 'not valid')
    end
  end

  def unsubscribe_verifier
    Rails.application.message_verifier('unsubscribe')
  end

  def set_last_checked_at
    self.last_checked_at = Time.now
  end

end

app/controllers/subscriptions_controller.rb
# The controller for actions related to the Subscriptions model
class SubscriptionsController < ApplicationController

  skip_before_action :authenticate_user!, :authenticate_user_from_token!, only: :unsubscribe
  before_action :authenticate_user!, only: :index
  before_action :find_subscription, only: [:destroy, :unsubscribe]
  before_action :set_breadcrumbs, only: :index

  def index
    @subscriptions = current_user.subscriptions.order('created_at DESC')
  end

  def create
    @subscription = current_user.subscriptions.build(subscription_params)

    if @subscription.save
      flash[:notice] = 'Subscription successfully created.'
      respond_to do |format|
        format.html { redirect_to subscriptions_path }
      end
    else
      flash[:error] = @subscription.errors.full_messages.join(", ")
      respond_to do |format|
        format.html { redirect_to :back }
      end
    end
  end

  def destroy
    authorize @subscription.user, :manage?
    if @subscription.destroy
      flash[:notice] = 'Subscription cancelled.'
      respond_to do |format|
        format.html { redirect_to subscriptions_path }
      end
    else
      respond_to do |format|
        format.html { render plain: 'There was a problem unsubscribing.', status: :unprocessable_entity }
      end
    end
  end

  def unsubscribe
    if @subscription.valid_unsubscribe_code?(params[:code]) && @subscription.destroy
      respond_to do |format|
        format.html
      end
    else
      respond_to do |format|
        format.html { render plain: 'Invalid code', status: :unprocessable_entity }
      end
    end
  end

  private

  def subscription_params
    subscribable_type = params[:subscription][:subscribable_type].constantize
    p = params.require(:subscription).permit(:frequency, :subscribable_type)
    p.merge(query: params[:q], facets: params.permit(*subscribable_type.facet_fields))
  end

  def find_subscription
    @subscription = Subscription.find(params[:id])
  end

  def set_breadcrumbs
    add_base_breadcrumbs('users')
    @breadcrumbs += [{ name: current_user.name, url: user_path(current_user) }, { name: 'Subscriptions' }]
  end
end

app/helpers/subscriptions_helper.rb
# The helper for Subscription classes
module SubscriptionsHelper

  def frequency_options_for_select
    options_for_select(Subscription::FREQUENCY.map { |k| [k[:key].to_s.humanize, k[:key]] })
  end

  def subscription_results_path(sub)
    polymorphic_path(*subscription_results_options(sub))
  end

  def subscription_results_url(sub)
    polymorphic_url(*subscription_results_options(sub))
  end

  def digest_event_title(event)
    title = neatly_printed_date_range(event.start, event.end)

    if event.city || event.country
      title << " | #{[event.city, event.country].reject(&:blank?).join(', ')}"
    end

    title
  end

  private

  def subscription_results_options(sub)
    max_age = Subscription::FREQUENCY.detect { |f| f[:key] == sub.frequency }.try(:[], :title)
    [sub.subscribable_type.constantize, sub.facets.merge(q: sub.query, max_age: max_age)]
  end

end

app/views/subscriptions/_subscribe_button.html.erb
<%
  show_email_sub = true
  show_calendar_sub = (type == 'Event')
%>

<% if show_calendar_sub || show_email_sub %>
  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Subscribe <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% if show_email_sub %>
          <li>
            <a href="#" data-toggle="modal" data-target="#subscribe-email-modal">
              <i class="fa fa-envelope-o"></i> Subscribe via email
            </a>
          </li>
      <% end %>
      <% if show_calendar_sub %>
          <li>
            <a href="#" data-toggle="modal" data-target="#subscribe-calendar-modal">
              <i class="fa fa-calendar-o"></i> Add to calendar
            </a>
          </li>
      <% end %>
    </ul>
  </div>

  <% if show_email_sub %>
      <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="subscribe-email-modal-title" id="subscribe-email-modal">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="subscribe-email-modal-title">Email Subscription</h4>
            </div>

            <div class="modal-body">
              <%= form_tag(subscriptions_path(search_and_facet_params)) do %>
                  <%= hidden_field_tag('subscription[subscribable_type]', type) %>
                  <div class="form-group">
                    <label for="frequency">Frequency</label>
                    <%= select_tag('subscription[frequency]', frequency_options_for_select, class: 'form-control', autocomplete: 'off') %>
                  </div>
                  <%= submit_tag('Subscribe', class: 'btn btn-primary') %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>

  <%= render partial: 'subscriptions/subscribe_to_calendar_modal' if show_calendar_sub %>
<% end %>

app/views/subscriptions/_subscribe_to_calendar_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="subscribe-modal-title" id="subscribe-calendar-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="subscribe-modal-title">Subscribe to Filter</h4>
      </div>

      <div class="modal-body">
        <label for="calendar-link">URL</label>
        <div class="input-group input-group-lg">
          <input id="calendar-link" type="text" class="form-control" value="<%= events_url({ format: :ics }.merge(search_and_facet_params)) -%>" readonly>
          <span class="input-group-btn">
            <button class="btn btn-default clipboard-btn" type="button" data-clipboard-target="#calendar-link" title="Click to copy">
              <i class="fa fa-clipboard" aria-hidden="true"></i>
            </button>
          </span>
        </div>
        <h3>Importing into Google Calendar</h3>
        <p>
        In the left-hand column of the <a href="https://calendar.google.com/calendar" target="_blank">Google Calendar</a> main view,
        click the arrow to the right of "Other calendars" and click "Add by URL". In the form that appears, paste in the URL from the box above, and click the button to confirm.
        </p>
        <%= image_tag 'calendar_howto.png', {:style=>"width:100%"} %>
        <p>
          Please note, it may take a while for newly created events in <%= TeSS::Config.site['title_short'] %> to synchronise with your Google Calendar.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/_subscription.html.erb
<div class="panel panel-default subscription">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-9">
        <p><strong>Category:</strong> <%= subscription.subscribable_type.humanize.pluralize %></p>
        <p><strong>Frequency:</strong> <%= subscription.frequency.to_s.capitalize %></p>
        <p><strong>Last email sent:</strong> <%= subscription.last_sent_at || 'Never' %></p>
        <p><strong>Created:</strong> <%= subscription.created_at %></p>

        <% if subscription.query.present? %>
            <p>
              <strong>Search term:</strong>
              <em><%= subscription.query %></em>
            </p>
        <% end %>

        <% if subscription.facets.present? %>
            <strong>Filters:</strong>
            <ul>
              <% subscription.facets.each do |facet, values| %>
                  <li>
                    <strong><%= facet.humanize %>:</strong>
                    <% Array(values).each do |value| %>
                      <span class="label label-default filter-button" title="<%= value -%>"><%= truncate(value.to_s, length: 30) %></span>
                    <% end %>
                  </li>
              <% end %>
            </ul>
        <% end %>
      </div>
      <div class="col-sm-3 text-right">
        <%= link_to 'Results', subscription_results_path(subscription), class: 'btn btn-primary' %>
        <%= link_to 'Cancel',
                    subscription,
                    method: 'delete',
                    data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                    class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/index.html.erb
<div class="wrapper">
  <div id="content">
    <h1>Subscriptions</h1>
    <%= render @subscriptions %>
    <% if @subscriptions.none? %>
        <span class="muted">You have no subscriptions.</span>
    <% end %>
  </div>
</div>

app/views/subscriptions/unsubscribe.html.erb
You have successfully unsubscribed.