config/routes.rb
Rails.application.routes.draw do
  concern :collaboratable do
    resources :collaborations, only: [:create, :destroy, :index, :show]
  end

  concern :activities do
    resources :activities, only: [:index]
  end

  get 'edam/terms' => 'edam#terms'
  get 'edam/topics' => 'edam#topics'
  get 'edam/operations' => 'edam#operations'

  if TeSS::Config.feature['workflows'] == true
    resources :workflows
  end

  get 'about' => 'about#tess', as: 'about'
  get 'about/registering' => 'about#registering', as: 'registering_resources'
  get 'about/developers' => 'about#developers', as: 'developers'
  get 'about/us' => 'about#us', as: 'us'

  get 'privacy' => 'static#privacy', as: 'privacy'

  post 'materials/check_exists' => 'materials#check_exists'
  post 'events/check_exists' => 'events#check_exists'
  post 'content_providers/check_exists' => 'content_providers#check_exists'
  post 'sources/check_exists' => 'sources#check_exists'

  if (ActiveRecord::Base.connection rescue false)
    devise_for :users, :controllers => {
      :registrations => 'tess_devise/registrations',
      :invitations => 'tess_devise/invitations',
      :omniauth_callbacks => 'callbacks'
    }
  end

  patch 'users/:id/change_token' => 'users#change_token', as: 'change_token'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'static#home'

  get 'static/home'

  resources :users do
    resource :ban, only: [:create, :new, :destroy]
  end

  resources :sources, concerns: :activities

  if TeSS::Config.feature['trainers'] == true
    resources :trainers, only: [:show, :index]
  end

  if TeSS::Config.feature['nodes'] == true
    resources :nodes, concerns: :activities
  end

  if TeSS::Config.feature['events'] == true
    resources :events, concerns: :activities do
      collection do
        get 'count'
      end
      member do
        get 'redirect'
        post 'add_term'
        post 'add_data'
        post 'reject_term'
        post 'reject_data'
        get 'report'
        patch 'report', to: 'events#update_report'
        get 'clone', to: 'events#clone'
      end
    end
  end

  if TeSS::Config.feature['packages'] == true
    resources :packages, concerns: :activities
  end

  if TeSS::Config.feature['workflows'] == true
    resources :workflows, concerns: [:collaboratable, :activities] do
      member do
        get 'fork'
        get 'embed'
      end
    end
  end

  if TeSS::Config.feature['providers'] == true
    resources :content_providers, concerns: :activities
  end

  if TeSS::Config.feature['materials'] == true
    resources :materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['e-learnings'] == true
    resources :elearning_materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['invitation'] == true
    get 'invitees' => 'users#invitees'
  end

  resources :subscriptions, only: [:show, :index, :create, :destroy] do
    member do
      get 'unsubscribe'
    end
  end

  get 'stars' => 'stars#index'
  post 'stars' => 'stars#create'
  delete 'stars' => 'stars#destroy'

  post 'materials/:id/update_packages' => 'materials#update_packages'
  post 'events/:id/update_packages' => 'events#update_packages'

  get 'search' => 'search#index'
  get 'test_url' => 'application#test_url'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "application#handle_error", :status_code => code
  end

  get 'curate/topic_suggestions' => 'curator#topic_suggestions'
  get 'curate/users' => 'curator#users'
  get 'curate' => 'curator#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'resolve/:prefix:type:id' => 'resolution#resolve', constraints: { prefix: /(.+\:)?/, type: /[a-zA-Z]/, id: /\d+/ }

end

app/models/elearning_material.rb
require 'rails/html/sanitizer'

class ElearningMaterial < Material
  def self.alias
    return "Material"  
  end
  def self.filter
    return {"resource_type"=>"e-learning"}
  end
end

app/controllers/elearning_materials_controller.rb
# The controller for actions related to the Elearning Materials model
class ElearningMaterialsController < MaterialsController
  def model_for_controller
    return "Material"
  end
end

app/views/elearning_materials/partials/_general_material_info.html.erb
<%= info_box('What are training materials?') do %>
    <%= render_markdown(MaterialsHelper::MATERIALS_INFO) %>
<% end %>

app/views/elearning_materials/partials/_material_schemaorg.html.erb
<div itemscope itemtype="http://schema.org/CreativeWork">
  <%= content_tag :span, material.title, { itemprop: 'name', content: material.title, class: 'schemaorg-element' } %>
  <%= content_tag :span, material.url, { itemprop: 'url', content: material.url, class: 'schemaorg-element' } %>
  <%= content_tag :span, material_url(material), { itemprop: 'sameAs', content: material_url(material), class: 'schemaorg-element' } %>
  <% if material.contact and not material.contact.empty? %>
    <%= content_tag :span, material.contact, { itemprop: 'contact', content: material.contact, class: 'schemaorg-element' } %>
  <% end %>
  <% if material.authors and not material.authors.empty? %>
    <% material.authors.each do |author| %>
        <span itemscope itemprop='author' itemtype="http://schema.org/Person">
            <%= content_tag 'span', author, { itemprop: 'name', content: author, class: 'schemaorg-element' } %>
        </span>
    <% end %>
  <% end %>

  <% if material.contributors and not material.contributors.empty? %>
    <% material.contributors.each do |contributor| %>
        <span itemscope itemprop='contributor' itemtype="http://schema.org/Person">
            <%= content_tag 'span', contributor,
                            { itemprop: 'name',
                              content: contributor,
                              class: 'schemaorg-element'
                            } %>
        </span>
    <% end %>
  <% end %>

  <% if material.scientific_topics and not material.scientific_topics.empty? %>
    <% material.scientific_topics.each do |scientific_topic| %>
      <%= content_tag 'span', scientific_topic.preferred_label,
                      { itemprop: 'genre',
                        content: scientific_topic.preferred_label,
                        class: 'schemaorg-element'
                      } %>
    <% end %>
  <% end %>

  <% if material.keywords and not material.keywords.empty? %>
    <% keywords = material.keywords.join(', ') %>
    <%= content_tag 'span', keywords, { itemprop: 'keywords', content: keywords, class: 'schemaorg-element' } %>
  <% end %>

  <% if material.target_audience and not material.target_audience.empty? %>
    <% material.target_audience.each do |target_audience| %>
        <span itemscope itemprop='audience' itemtype="http://schema.org/PeopleAudience">
            <%= content_tag 'span', target_audience,
                            { itemprop: 'name',
                              content: target_audience,
                              class: 'schemaorg-element'
                            } %>
        </span>
    <% end %>
  <% end %>

  <%= content_tag 'span', material.remote_created_date,
                  { itemprop: 'dateCreated',
                    content: material.remote_created_date,
                    class: 'schemaorg-element' } if material.remote_created_date and not material.remote_created_date.to_s.empty? %>
  <%= content_tag 'span', material.remote_updated_date,
                  { itemprop: 'dateModified',
                    content: material.remote_updated_date,
                    class: 'schemaorg-element' } if material.remote_updated_date and not material.remote_updated_date.to_s.empty? %>
</div>

app/views/elearning_materials/partials/_twitter_card.html.erb
<% content_for :og_header do %>
  <%= tag(:meta, name: "twitter:card", content: 'summary') %>
  <%= tag(:meta, name: "twitter:site", content: TeSS::Config.twitter_handle) %>
  <%= tag(:meta, name: "twitter:creator", content: TeSS::Config.twitter_handle) %>
  <%= tag(:meta, property: "og:url", content: request.original_url) %>
  <%= tag(:meta, property: "og:title", content: material.title) %>
  <%= tag(:meta, property: "og:description", content: material.description) %>
  <%= tag(:meta, property: "og:image", content: asset_url(TeSS::Config.site['logo_open_graph'])) %>
<% end %>