config/routes.rb
Rails.application.routes.draw do
  concern :collaboratable do
    resources :collaborations, only: [:create, :destroy, :index, :show]
  end

  concern :activities do
    resources :activities, only: [:index]
  end

  get 'edam/terms' => 'edam#terms'
  get 'edam/topics' => 'edam#topics'
  get 'edam/operations' => 'edam#operations'

  if TeSS::Config.feature['workflows'] == true
    resources :workflows
  end

  get 'about' => 'about#tess', as: 'about'
  get 'about/registering' => 'about#registering', as: 'registering_resources'
  get 'about/developers' => 'about#developers', as: 'developers'
  get 'about/us' => 'about#us', as: 'us'

  get 'privacy' => 'static#privacy', as: 'privacy'

  post 'materials/check_exists' => 'materials#check_exists'
  post 'events/check_exists' => 'events#check_exists'
  post 'content_providers/check_exists' => 'content_providers#check_exists'
  post 'sources/check_exists' => 'sources#check_exists'

  if (ActiveRecord::Base.connection rescue false)
    devise_for :users, :controllers => {
      :registrations => 'tess_devise/registrations',
      :invitations => 'tess_devise/invitations',
      :omniauth_callbacks => 'callbacks'
    }
  end

  patch 'users/:id/change_token' => 'users#change_token', as: 'change_token'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'static#home'

  get 'static/home'

  resources :users do
    resource :ban, only: [:create, :new, :destroy]
  end

  resources :sources, concerns: :activities

  if TeSS::Config.feature['trainers'] == true
    resources :trainers, only: [:show, :index]
  end

  if TeSS::Config.feature['nodes'] == true
    resources :nodes, concerns: :activities
  end

  if TeSS::Config.feature['events'] == true
    resources :events, concerns: :activities do
      collection do
        get 'count'
      end
      member do
        get 'redirect'
        post 'add_term'
        post 'add_data'
        post 'reject_term'
        post 'reject_data'
        get 'report'
        patch 'report', to: 'events#update_report'
        get 'clone', to: 'events#clone'
      end
    end
  end

  if TeSS::Config.feature['packages'] == true
    resources :packages, concerns: :activities
  end

  if TeSS::Config.feature['workflows'] == true
    resources :workflows, concerns: [:collaboratable, :activities] do
      member do
        get 'fork'
        get 'embed'
      end
    end
  end

  if TeSS::Config.feature['providers'] == true
    resources :content_providers, concerns: :activities
  end

  if TeSS::Config.feature['materials'] == true
    resources :materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['e-learnings'] == true
    resources :elearning_materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['invitation'] == true
    get 'invitees' => 'users#invitees'
  end

  resources :subscriptions, only: [:show, :index, :create, :destroy] do
    member do
      get 'unsubscribe'
    end
  end

  get 'stars' => 'stars#index'
  post 'stars' => 'stars#create'
  delete 'stars' => 'stars#destroy'

  post 'materials/:id/update_packages' => 'materials#update_packages'
  post 'events/:id/update_packages' => 'events#update_packages'

  get 'search' => 'search#index'
  get 'test_url' => 'application#test_url'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "application#handle_error", :status_code => code
  end

  get 'curate/topic_suggestions' => 'curator#topic_suggestions'
  get 'curate/users' => 'curator#users'
  get 'curate' => 'curator#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'resolve/:prefix:type:id' => 'resolution#resolve', constraints: { prefix: /(.+\:)?/, type: /[a-zA-Z]/, id: /\d+/ }

end

app/models/content_provider.rb
class ContentProvider < ApplicationRecord

  include PublicActivity::Common
  include LogParameterChanges
  include Searchable
  include IdentifiersDotOrg
  include HasFriendlyId
  include CurationQueue

  has_many :materials, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :sources, :dependent => :destroy

  belongs_to :user
  belongs_to :node, optional: true

  has_and_belongs_to_many :editors, class_name: "User"

  attribute :approved_editors, :string, array: true
  attribute :contact, :string

  #has_many :content_provider_users
  #has_many :editors, through: :users, source: :user, inverse_of: :providers

  delegate :name, to: :node, prefix: true, allow_nil: true

  # Remove trailing and squeezes (:squish option) white spaces inside the string (before_validation):
  # e.g. "James     Bond  " => "James Bond"
  auto_strip_attributes :title, :description, :url, :image_url, :squish => false

  validates :title, :url, presence: true

  # Validate the URL is in correct format via valid_url gem
  validates :url, url: true

  clean_array_fields(:keywords, :approved_editors)

  # The order of these determines which providers have precedence when scraping.
  # Low -> High
  PROVIDER_TYPE = ['Portal', 'Organisation', 'Project']
  has_image(placeholder: TeSS::Config.placeholder['provider'])

  if TeSS::Config.solr_enabled
    # :nocov:
    searchable do
      # full text fields
      text :title
      text :description
      text :keywords
      # sort title
      string :sort_title do
        title.downcase.gsub(/^(an?|the) /, '')
      end
      # other fields
      string :title
      string :keywords, :multiple => true
      string :node, :multiple => true do
        unless self.node.blank?
          self.node.name
        end
      end
      integer :count do
        if self.events.count > self.materials.count
          self.events.count
        else
          self.materials.count
        end
      end
      integer :user_id # Used for shadowbans
      time :updated_at
    end
    # :nocov:
  end

  update_suggestions(:keywords)

  def self.facet_fields
    %w( keywords )
  end

  def node_name= name
    self.node = Node.find_by_name(name)
  end

  def precedence
    PROVIDER_TYPE.index(content_provider_type)
  end

  def self.check_exists(content_provider_params)
    given_content_provider = self.new(content_provider_params)
    content_provider = nil

    if given_content_provider.url.present?
      content_provider = self.find_by_url(given_content_provider.url)
    end

    if given_content_provider.title.present?
      content_provider ||= self.where(title: given_content_provider.title).last
    end

    content_provider
  end

  def self.identifiers_dot_org_key
    'p'
  end

  def add_editor(editor)
    if !editor.nil? and !editors.include?(editor) and !user.nil? and user.id != editor.id
      editors << editor
      save!
      editor.editables.reload
    end
  end

  def remove_editor(editor)
    if !editor.nil? and editors.include?(editor)
      # remove from array
      editors.delete(editor)
      save!
      editor.editables.reload

      # transfer events to the provider's user
      editor.events.each do |event|
        if !event.content_provider.nil? and event.content_provider.id == id
          event.user = user
          event.save!
        end
      end

      # transfer materials to the provider's user
      editor.materials.each do |material|
        if !material.content_provider.nil? and material.content_provider.id == id
          material.user = user
          material.save!
        end
      end
      editor.reload
      editor.save!
    end

  end

  def approved_editors
    result = []
    editors.each { |editor| result << editor.username }
    #puts "get approved_editors: found #{result.size} editors"
    return result
  end

  def approved_editors= values
    #puts "set approved_editors: user count #{values.size}"
    editors_list = []
    values.each do |item|
      if !item.nil? and !item.blank?
        list_user = User.find_by_username(item)
        editors_list << list_user if !list_user.nil?
      end
    end
    # add missing
    editors_list.each { |item| add_editor(item) if !editors.include?(item) }
    # remove old
    editors.each { |item| remove_editor(item) if !editors_list.include?(item) }
  end

end

app/controllers/content_providers_controller.rb
# The controller for actions related to the Content Providers model
class ContentProvidersController < ApplicationController
  before_action :set_content_provider, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumbs

  include SearchableIndex

  def index
    respond_to do |format|
      format.html
      format.json
      format.json_api { render({ json: @content_providers }.merge(api_collection_properties)) }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json
      format.json_api { render json: @content_provider }
    end
  end

  def new
    authorize ContentProvider
    @content_provider = ContentProvider.new
  end

  def edit
    authorize @content_provider
    @editor_usernames
  end

  # POST /events/check_exists
  # POST /events/check_exists.json
  def check_exists
    @content_provider = ContentProvider.check_exists(content_provider_params)

    if @content_provider
      respond_to do |format|
        format.html { redirect_to @content_provider }
        format.json { render :show, location: @content_provider }
      end
    else
      respond_to do |format|
        format.html { render :nothing => true, :status => 200, :content_type => 'text/html' }
        format.json { render json: {}, :status => 200, :content_type => 'application/json' }
      end
    end
  end

  def create
    authorize ContentProvider
    @content_provider = ContentProvider.new(content_provider_params)
    @content_provider.user = current_user

    respond_to do |format|
      if @content_provider.save
        @content_provider.create_activity :create, owner: current_user
        format.html { redirect_to @content_provider, notice: 'Content Provider was successfully created.' }
        format.json { render :show, status: :created, location: @content_provider }
      else
        format.html { render :new }
        format.json { render json: @content_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @content_provider
    respond_to do |format|
      if @content_provider.update(content_provider_params)
        @content_provider.create_activity(:update, owner: current_user) if @content_provider.log_update_activity?
        format.html { redirect_to @content_provider, notice: 'Content Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_provider }
      else
        format.html { render :edit }
        format.json { render json: @content_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @content_provider
    @content_provider.create_activity :destroy, owner: current_user
    @content_provider.destroy
    respond_to do |format|
      format.html { redirect_to content_providers_url, notice: 'Content Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content_provider
    @content_provider = ContentProvider.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_provider_params
    # For calls to create/update content_provider - get the node id from node name, if node id is not passed
    if (params[:content_provider][:node_id].blank? && !params[:content_provider][:node_name].blank?)
      node = Node.find_by_name(params[:content_provider][:node_name])
      params[:content_provider][:node_id] = node.id unless node.blank?
    end

    params[:content_provider].delete :node_name

    permitted = [:title, :url, :image, :image_url, :description, :id, :content_provider_type, :node_id, :contact,
        {:keywords => []}, :remote_updated_date, :remote_created_date, { :approved_editors => [] },
        :local_updated_date, :remote_updated_date, :node_name, :user_id]

    permitted.delete(:user_id) unless current_user && current_user.is_admin?

    params.require(:content_provider).permit(permitted)
  end
end

app/helpers/content_providers_helper.rb
# The helper for Content Providers
module ContentProvidersHelper
  CONTENT_PROVIDERS_INFO = I18n.t 'providers.info'
end

app/views/content_providers/_content_provider.html.erb
<li class="masonry-brick media-item ">
  <%= image_tag content_provider.image.url, class: "media-image listing_image" %>
  <h3 class="media-heading"><%= content_provider.title %></h3>
  <p><%= truncate(content_provider.description, length: 100, separator: ' ') %></p>

  <% if content_provider.materials.length > 0 %>
    <div><strong><%= pluralize(content_provider.materials.length, 'training material') %></strong></div>
  <% end %>

  <% if content_provider.events.length > 0 %>
    <div>
      <strong><%= pluralize(content_provider.events.not_finished.length, 'upcoming event') %></strong>
      <em>(<%= pluralize(content_provider.events.finished.length, 'past event') %>)</em>
    </div>
  <% end %>

  <%= link_to '', content_provider, :class => "media-view" %>

  <%= render partial: 'content_providers/partials/content_provider_schemaorg',
             locals: { content_provider: content_provider } %>
</li>

app/views/content_providers/_form.html.erb
<%= simple_form_for @content_provider, html: { class: "content_provider", multipart: true } do |f| %>

  <%= render partial: 'common/error_summary', locals: { resource: @content_provider } %>

  <%= f.input :title, as: :string %>

  <%= render partial: 'common/url_checker', locals: { f: f, url: content_providers_check_exists_path, title: '' } %>

  <%= f.input :contact, as: :string %>

  <%= f.input :description, as: :markdown_area, input_html: { rows: '10' } %>

  <div class="form-group">
    <%= render partial: 'common/image_form', locals: { form: f } %>
  </div>

  <%= f.input :content_provider_type, label: 'Type', collection: ContentProvider::PROVIDER_TYPE, include_blank: false %>

  <% if current_user.is_admin? %>
    <%= f.input :user_id, label: 'Owner', collection: User.order('LOWER(users.username)').all%>
  <% end %>

  <%= f.dropdown :approved_editors, options: get_list_of_user_names, label: 'Approved Editors' %>

  <%= f.multi_input :keywords %>


  <!-- Nodes: check feature enabled -->
  <% if TeSS::Config.feature['nodes'] %>
    <%= f.input :node_id, label: 'ELIXIR node', collection: Node.all, label_method: :title %>
  <% end %>

  <div class="form-group">
    <%= f.submit (f.object.new_record? ? "Register" : "Update") + " content provider", class: 'btn btn-primary' %>
    <%= link_to 'Back', content_providers_path, class: "btn btn-info" %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                content_providers_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/content_providers/edit.html.erb
<%- model_class = ContentProvider -%>
<div class="row wrapper">
  <div class="col-md-12">
    <div class="page-header">
      <%= page_title(t('.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize.downcase)) %>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-push-8">
        <%= render :partial => 'content_providers/partials/general_content_provider_info' %>
      </div>
      <div class="col-md-8 col-md-pull-4">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/content_providers/index.html.erb
<div class="wrapper">
  <% if TeSS::Config.solr_enabled %>
    <div id="sidebar" class="popout-sidebar">
      <%= render partial: "search/common/facet_sidebar",
                 locals: { resources: @content_providers_results,
                           resource_type: ContentProvider } %>
    </div>
  <% end %>

  <div id="content">
    <div class="row">
      <%= link_to new_content_provider_path, class: 'btn btn-primary' do %>
        <i class="fa fa-plus-square"></i> Register content provider
      <% end %>
      <div class="pull-right">
        <%= info_button('What are content providers in ' +
                          TeSS::Config.site['title_short'] + '?') do %>
          <%= render_markdown(ContentProvidersHelper::CONTENT_PROVIDERS_INFO) %>
        <% end %>
      </div>
    </div>

    <% if TeSS::Config.solr_enabled %>
      <div class="row">
        <%= render partial: "search/common/search_box",
                   locals: { resource_path: content_providers_path } %>
        <button class="btn btn-default" id="sidebar-toggle" type="button"
                autocomplete="off">
          <i class="fa fa-filter"></i> Filters
        </button>
      </div>
      <div class="row">
        <%= render partial: "search/common/sort_by",
                   locals: { resources: @content_providers } %>
        <%= render partial: "search/common/search_info",
                   locals: { resources: @content_providers_results,
                             resource_type: 'content_provider' } %>
        <%= render partial: "search/common/search_filters",
                   locals: { resources: @content_providers_results } %>
      </div>
    <% end %>

    <%= render partial: "search/common/pagination_bar",
               locals: { resources: @content_providers } %>

    <hr>

    <%= render partial: 'common/masonry_grid', locals: { objects: @content_providers } %>
  </div>
</div>

app/views/content_providers/new.html.erb
<%- model_class = ContentProvider -%>
<div class="row wrapper">
  <div class="col-md-12">
    <div class="page-header">
      <%= page_title(t('.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize.downcase)) %>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-push-8">
        <%= render :partial => 'content_providers/partials/general_content_provider_info' %>
      </div>
      <div class="col-md-8 col-md-pull-4">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/content_providers/show.html.erb
<% events = @content_provider.events.from_verified_users %>
<% materials = @content_provider.materials.from_verified_users %>

<div class="wrapper collapsing-wrapper">
  <%# SIDEBAR %>
  <div class="collapsing-sidebar" id="sidebar">
    <%= render :partial => "content_providers/partials/content_provider_sidebar",
               :locals => { content_provider: @content_provider } %>
  </div>
  <div id="content">
    <div class="row">
      <% if !current_user.nil? and policy(@content_provider).update? %>
        <div class="content_action pull-left">
          <%= link_to sources_path(content_provider: @content_provider.title),
                      class: 'btn btn-primary align-self-end' do %>
            Ingestion Sources
          <% end %>
        </div>
      <% end %>

      <div class="content_action pull-right">
        <%= link_to t('.back', :default => t("helpers.links.back")),
                    content_providers_path, :class => 'btn btn-info' %>

        <%= render partial: 'common/identifiers_dot_org_button',
                   locals: { resource: @content_provider } if TeSS::Config.identifiers_prefix %>

        <% if !current_user.nil? and policy(@content_provider).update? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_content_provider_path(@content_provider), :class => 'btn btn-primary' %>
        <% end %>

        <% if !current_user.nil? and policy(@content_provider).destroy? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      content_provider_path(@content_provider),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <p>
        <%= link_to(image_tag(@content_provider.image.url, :class => "medium-content-provider-logo"),
                    @content_provider.url, :target => '_blank',
                    :onclick => "getOutboundLink('#{@content_provider.url}'); return true;") %>
      </p>

      <p>
        <%= link_to @content_provider.title, @content_provider.url, :class => "h5",
                    :target => '_blank',
                    :onclick => "getOutboundLink('#{@content_provider.url}'); return true;" %>
      </p>

      <% unless @content_provider.contact.blank? %>
        <p><strong>Contact:&nbsp;</strong><%= @content_provider.contact %></p>
      <% end %>

      <% unless @content_provider.description.blank? %>
        <p class="minimise"><%= render_markdown @content_provider.description %></p>
      <% end %>

      <%= render partial: 'content_providers/partials/content_provider_schemaorg',
                 locals: { content_provider: @content_provider } %>

      <%= render partial: 'content_providers/partials/twitter_card',
                 locals: { content_provider: @content_provider } %>
    </div>

    <div class="row">
      <ul class="nav nav-tabs">
        <%= tab('Materials', icon_class_for_model('materials'), 'materials', active: materials.any? || events.none?,
                disabled: { check: materials.none?, message: 'No associated training materials' },
                count: materials.count) %>

        <%= tab('Events', icon_class_for_model('events'), 'events', active: materials.none? && events.any?,
                disabled: { check: events.none?, message: 'No associated events' },
                count: events.count) %>

        <%= tab('Activity log', icon_class_for_model('activity_logs'), 'activity_log',
                disabled: { check: @content_provider.activities.none?, message: 'No activities recorded' }) %>
      </ul>

      <div class="tab-content">
        <div id="materials" class="tab-pane fade 
              <%= "in active" if materials.any? || events.none? %>
          ">
          <div class="row">
            <% limited_materials = materials.count > 30 ? materials.limit(30) : materials %>
            <div class="search-results-count">
              <%= (limited_materials.count > 0 ? "Showing" : "Found") + " #{pluralize(materials.count, "material")}#{(materials.count > 30) ? " out of #{materials.count}" : ''}." %>
              <%= link_to('View all results.', materials_path(content_provider: @content_provider.title)) if (materials.count > 30) %>
            </div>

            <% materials.each do |material| %>
              <%= render material %>
            <% end %>
          </div>
        </div>
        <div id="events" class="tab-pane fade
              <%= "in active" if materials.none? && events.any? %>
          ">
          <div class="row">
            <% upcoming_events = events.select(&:upcoming?) %>
            <% past_events = events.select(&:expired?) %>

            <div class="row">
              <% limited_events = upcoming_events.count > 30 ? upcoming_events.first(30) : upcoming_events %>
              <div class="search-results-count">
                <%= (upcoming_events.count > 0 ? "Showing" : "Found") + " #{pluralize(limited_events.count, "upcoming event")}#{(upcoming_events.count > 30) ? " out of #{upcoming_events.count}" : ''}." %>
                <%= "Found #{pluralize(past_events.count, "past event")}." %>
                <%= link_to('View all results.', events_path(content_provider: @content_provider.title, include_expired: true)) if (upcoming_events.count > 30 || past_events.count > 0) %>
              </div>
              <% if upcoming_events.count > 0 %>
                <ul class="masonry media-grid" style="margin-top: 15px;">
                  <% upcoming_events.each do |upcoming_event| %>
                    <%= render upcoming_event %>
                  <% end %>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
        <div id="activity_log" class="tab-pane fade" data-activity-path="<%= content_provider_activities_path(@content_provider) -%>">
          <%= image_tag('ajax-loader.gif') %>
        </div>
      </div>
    </div>
  </div>
</div>