config/routes.rb
Rails.application.routes.draw do
  concern :collaboratable do
    resources :collaborations, only: [:create, :destroy, :index, :show]
  end

  concern :activities do
    resources :activities, only: [:index]
  end

  get 'edam/terms' => 'edam#terms'
  get 'edam/topics' => 'edam#topics'
  get 'edam/operations' => 'edam#operations'

  if TeSS::Config.feature['workflows'] == true
    resources :workflows
  end

  get 'about' => 'about#tess', as: 'about'
  get 'about/registering' => 'about#registering', as: 'registering_resources'
  get 'about/developers' => 'about#developers', as: 'developers'
  get 'about/us' => 'about#us', as: 'us'

  get 'privacy' => 'static#privacy', as: 'privacy'

  post 'materials/check_exists' => 'materials#check_exists'
  post 'events/check_exists' => 'events#check_exists'
  post 'content_providers/check_exists' => 'content_providers#check_exists'
  post 'sources/check_exists' => 'sources#check_exists'

  if (ActiveRecord::Base.connection rescue false)
    devise_for :users, :controllers => {
      :registrations => 'tess_devise/registrations',
      :invitations => 'tess_devise/invitations',
      :omniauth_callbacks => 'callbacks'
    }
  end

  patch 'users/:id/change_token' => 'users#change_token', as: 'change_token'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'static#home'

  get 'static/home'

  resources :users do
    resource :ban, only: [:create, :new, :destroy]
  end

  resources :sources, concerns: :activities

  if TeSS::Config.feature['trainers'] == true
    resources :trainers, only: [:show, :index]
  end

  if TeSS::Config.feature['nodes'] == true
    resources :nodes, concerns: :activities
  end

  if TeSS::Config.feature['events'] == true
    resources :events, concerns: :activities do
      collection do
        get 'count'
      end
      member do
        get 'redirect'
        post 'add_term'
        post 'add_data'
        post 'reject_term'
        post 'reject_data'
        get 'report'
        patch 'report', to: 'events#update_report'
        get 'clone', to: 'events#clone'
      end
    end
  end

  if TeSS::Config.feature['packages'] == true
    resources :packages, concerns: :activities
  end

  if TeSS::Config.feature['workflows'] == true
    resources :workflows, concerns: [:collaboratable, :activities] do
      member do
        get 'fork'
        get 'embed'
      end
    end
  end

  if TeSS::Config.feature['providers'] == true
    resources :content_providers, concerns: :activities
  end

  if TeSS::Config.feature['materials'] == true
    resources :materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['e-learnings'] == true
    resources :elearning_materials, concerns: :activities do
      member do
        post :reject_term
        post :reject_data
        post :add_term
        post :add_data
      end
      collection do
        get 'count'
      end
    end
  end

  if TeSS::Config.feature['invitation'] == true
    get 'invitees' => 'users#invitees'
  end

  resources :subscriptions, only: [:show, :index, :create, :destroy] do
    member do
      get 'unsubscribe'
    end
  end

  get 'stars' => 'stars#index'
  post 'stars' => 'stars#create'
  delete 'stars' => 'stars#destroy'

  post 'materials/:id/update_packages' => 'materials#update_packages'
  post 'events/:id/update_packages' => 'events#update_packages'

  get 'search' => 'search#index'
  get 'test_url' => 'application#test_url'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "application#handle_error", :status_code => code
  end

  get 'curate/topic_suggestions' => 'curator#topic_suggestions'
  get 'curate/users' => 'curator#users'
  get 'curate' => 'curator#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'resolve/:prefix:type:id' => 'resolution#resolve', constraints: { prefix: /(.+\:)?/, type: /[a-zA-Z]/, id: /\d+/ }

end

app/controllers/about_controller.rb
# The controller for actions related to the about pages
class AboutController < ApplicationController

  skip_before_action :authenticate_user!, :authenticate_user_from_token!
  
  def tess
  end

  def us
  end

  def registering
  end

  def developers
  end

end

app/views/about/_about_nav.html.erb
<!-- SIDEBAR -->
<nav class="about-page-menu">

  <!-- WHAT IS TESS -->
  <ul class="nav nav-stacked">
    <li class="<%= show_active(show, 'home') %>">
      <%= link_to 'What is ' + TeSS::Config.site['title_short'] + '?', about_path %>
    </li>
    <ul class="nav nav-stacked">
      <li><%= link_to 'What we catalogue', about_path(:anchor => 'events') %></li>
      <li><%= link_to 'Subscribing to notifications', about_path(:anchor => 'subscribe') %></li>
      <li><%= link_to 'Widgets & API', about_path(:anchor => 'widget') %></li>
    </ul>
  </ul>

  <!-- REGISTERING YOUR RESOURCES -->
  <ul class="nav nav-stacked">
    <li class="<%= show_active(show, 'registering') %>">
      <%= link_to 'Registering Content', registering_resources_path %>
    </li>
    <ul class="nav nav-stacked">
      <li><%= link_to 'Automatic Registration', registering_resources_path(:anchor => 'automatic') %></li>
      <li><%= link_to 'Manual Registration', registering_resources_path(:anchor => 'manual') %></li>
    </ul>
  </ul>


  <!-- DEVELOPERS -->
  <ul class="nav nav-stacked">
    <li class="<%= show_active(show, 'developers') %>">
      <%= link_to 'Developers', developers_path %>
    </li>
    <ul class="nav nav-stacked">
      <li><%= link_to 'Code and Data', developers_path(:anchor => 'code_and_data') %></li>
      <li><%= link_to 'Widgets', developers_path(:anchor => 'widgets') %></li>
      <li><%= link_to 'API', developers_path(:anchor => 'api') %></li>
    </ul>
  </ul>

  <!-- ABOUT US -->
  <ul class="nav nav-stacked">
    <li class="<%= show_active(show, 'us') %>">
      <%= link_to 'About Us', us_path %>
    </li>
    <ul class="nav nav-stacked">
      <!--li><%= link_to 'TeSS Club', us_path(:anchor => 'tess-club') %></li-->
      <li><%= link_to 'Contact', us_path(:anchor => 'contact') %></li>
      <li><%= link_to 'The Team', us_path(:anchor => 'team') %></li>
      <li><%= link_to 'Funding', us_path(:anchor => 'funding') %></li>
      <li><%= link_to 'Acknowledgements', us_path(:anchor => 'acknowledgments') %></li>
    </ul>
  </ul>
</nav>

app/views/about/_elixir_widget_example.erb
<p>  Below is a live example of the TeSS Maps widget.</p>

<hr/>

<link rel="stylesheet" property="stylesheet" href="https://elixirtess.github.io/TeSS_widgets/css/tess-widget.css"/>

<div id="tess-widget-google-map" class="tess-widget tess-widget-google-map">

  <script>
      function initTeSSWidgets() {
          TessWidget.Events(document.getElementById('tess-widget-google-map'),
              'GoogleMap',
              {
                  opts: {
                      apiKey: <%= Rails.application.secrets.google_maps_api_key %> // Get your own API key!
                  },
                  params: {
                      country: [<%== raw t 'developer.gmaps_countries' %>],
                      pageSize: 500
                  }
              });
      }
  </script>

  <script async="" defer="" src="https://elixirtess.github.io/TeSS_widgets/js/tess-widget-standalone.js"
          onload="initTeSSWidgets()">
  </script>

</div>

<hr>

app/views/about/_links.html.erb
<div class="quick-links">
<%= link_to 'What is ' + TeSS::Config.site['title_short'] + '?', about_path, :class => "#{'selected-tab' if show=='tess'}"%>
| <%= link_to 'How to Register', registering_resources_path, :class => "#{'selected-tab' if show=='registering'}"%>
| <%= link_to 'Developers Guide', developers_path, :class => "#{'selected-tab' if show=='developer'}"%>
| <%= link_to 'About us', us_path, :class => "#{'selected-tab' if show=='about'}"%>
</div>

app/views/about/_partner_orgs.erb
<div class='partner-logos'>

  <%= link_to 'https://aaf.edu.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/AAF-Logo.png', alt: 'Australian Access Federation', style: 'height: 40px;' %>
  <% end %>

  <%= link_to 'https://www.asdaf.space/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/ASDAF-Logo.png', alt: 'Australian Space Data Analysis Facility', style: 'height: 40px;' %>
  <% end %>

  <%= link_to 'https://www.biocommons.org.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/Australian-Biocommons-Logo.png', alt: 'Australian Biocommons', style: 'height: 50px;' %>
  <% end %>

  <%= link_to 'https://www.deakin.edu.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/Deakin-Logo.png', style: 'height: 60px;' %>
  <% end %>

  <%= link_to 'https://www.federation.edu.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/Federation-Logo.png', alt: 'Federation University', style: 'height: 38px;' %>
  <% end %>

  <%= link_to 'https://www.intersect.org.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/Intersect-Australia-Logo.png', alt: 'Intersect Australia' %>
  <% end %>

  <%= link_to 'https://www.monash.edu/it/dsai', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/DSAI-Logo.png',
                  alt: 'Department of Data Science and Artificial Intelligence, Monash University' %>
  <% end %>

  <%= link_to 'https://www.qcif.edu.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/QCIF-Logo.png',
                  alt: 'Queensland Cyber Infrastructure Foundation', style: 'height: 48px;'%>
  <% end %>

  <%= link_to 'https://www.nci.org.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/NCI-Australia-Logo.png',
                  alt: 'National Computational Infrastructure Australia' %>
  <% end %>

  <%= link_to 'https://www.newcastle.edu.au/', class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/Newcastle-Logo.png', style: 'height: 40px;' %>
  <% end %>

  <%= link_to 'https://www.sydney.edu.au/researc/facilities/sydney-informatics-hub.html',
              class: 'partner-logo', target: '_blank' do %>
    <%= image_tag 'supporters/UoS-Logo.png', alt: 'Sydney Informatics Hub', style: 'height: 60px;' %>
  <% end %>

</div>
<br/>

app/views/about/developers.erb
<div class="wrapper">

  <div id="sidebar" class="popout-sidebar">
    <%= render :partial => 'about_nav', locals: { show: 'developers' } %>
  </div>

  <div id="content" class="">
    <div class="about-block">
      <%= render :partial => 'links', :locals => { 'show': 'developer' } %>

      <!-- ABOUT TESS DATA -->
      <div class="row">
        <div class="odd-about-block">
          <div id='code_and_data' class="h3">For Developers</div>

          <%== raw t 'developer.license' %>

          <div class="row">
            <div class="col-lg-5 5 open-access-box">
              <div class="h2 licence-title">Software</div>
              <div class="open-access-location">
                <%= link_to TeSS::Config.site['repository'], target: '_blank' do %>
                  <div class="register-condition-graphic">
                    <%= image_tag 'about/GitHub-Mark-64px.png', class: "" %>
                  </div>
                  <div class="register-condition">The source code for <%= TeSS::Config.site['title_short'] %>
                    is available on GitHub
                  </div>
                <% end %>
              </div>
              <div class="open-access-licence">
                <%= link_to TeSS::Config.site['repository'] + '/blob/master/LICENSE', target: '_blank' do %>
                  <div class="register-condition-graphic"><i class="fa fa-code licence-logo"></i></div>
                  <div class="register-condition">Source code is available under the
                    <%== raw t 'developer.code_license' %> license
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col-lg-5 open-access-box">
              <div class="h2 licence-title">Data</div>
              <%= link_to developers_path(:anchor => 'api') do %>
                <div class="open-access-location">
                  <div class="register-condition-graphic"><i class="fa fa-plug licence-logo"></i></div>
                  <div class="register-condition">
                    Data in <%= TeSS::Config.site['title_short'] %> can be accessed via our API
                  </div>
                </div>
              <% end %>
              <div class="open-access-licence">
                <div class="register-condition-graphic"><i class="fa fa-database licence-logo"></i></div>
                <%= link_to 'https://creativecommons.org/licenses/by/4.0/', target: '_blank' do %>
                  <div class="register-condition">Data are made available under the
                    <%== raw t 'developer.data_license' %> license
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Widgets -->
      <div class="row">
        <div class="even-about-block">
          <div class="h3" id="widgets">Widgets</div>
          <p><%== raw t 'developer.widgets' %></p>
          <p><%= link_to t('developer.widgets_available'), class: 'btn btn-primary', target: '_blank' do %>
              View Our Available Widgets
            <% end %></p>
          <%= render :partial => 'about/' + TeSS::Config.site['widget_example'] %>
          <%== raw t 'developer.widgets_mailing' %>
        </div>
      </div>

      <!-- API -->
      <div class="row">
        <div class="odd-about-block">
          <div class="h4" id="api">API</div>
          <span>
            <p><%= TeSS::Config.site['title_short'] %> has a fully functioning
              <a href="http://jsonapi.org/" target="_blank">JSON API</a>.
              You can explore our JSON-API by appending .json_api to the end of the URL of most pages
              (excluding parameters). For example:</p>

            <!-- Events -->
            <% if TeSS::Config.feature['events'] %>
            <p><code>
               <a href="<%= TeSS::Config.base_url %><%== raw t 'developer.api_example_1' %>">
                 <%= TeSS::Config.base_url %><%== raw t 'developer.api_example_1' %></a>
            </code></p>
            <% end %>

            <!-- Materials -->
            <% if TeSS::Config.feature['materials'] %>
            <p><code>
               <a href="<%= TeSS::Config.base_url %><%== raw t 'developer.api_example_3' %>">
                 <%= TeSS::Config.base_url %><%== raw t 'developer.api_example_3' %> </a>
            </code></p>
            <% end %>

            <!-- Providers -->
            <% if TeSS::Config.feature['providers'] %>
            <p><code>
               <a href="<%= TeSS::Config.base_url %><%== raw t 'developer.api_example_4' %>">
                               <%= TeSS::Config.base_url %><%== raw t 'developer.api_example_4' %> </a>
            </code></p>
            <% end %>

            <!-- Workflows -->
            <% if TeSS::Config.feature['workflows'] %>
            <p><code>
               <a href="<%= TeSS::Config.base_url %><%== raw t 'developer.api_example_5' %>">
                               <%= TeSS::Config.base_url %><%== raw t 'developer.api_example_5' %> </a>
            </code></p>
            <% end %>

            <%== raw t 'developer.swaggerhub' -%>
           </span>
        </div>
      </div>
    </div>
    <%= render :partial => 'links', :locals => { 'show': 'developer' } %>
  </div>
</div>
</div>
</body>

app/views/about/registering.html.erb
<div class="wrapper">

  <div id="sidebar" class="popout-sidebar">
    <%= render :partial => 'about_nav', locals: { show: 'registering' } %>
  </div>

  <div id="content" class="">
    <div class="about-block">
      <%= render :partial => 'links', :locals => { 'show': 'registering' } %>

      <!-- REGISTERING CONTENT IN TESS -->
      <div class="row">
        <div id='how' class="h3">Registering Resources in <%= TeSS::Config.site['title_short'] %></div>
        <%= raw t 'register.resources' %>

        <div class="row">
          <div class="col-md-3 motivation_box">
            <div class="include-where">&hellip; in <%= TeSS::Config.site['title_short'] %>
            </div>
            <div class="include-where-graphic">
              <%= image_tag 'about/events_listing.png', size: "200x200" %>
            </div>
            <div class="include-where-text">
              Be seen by thousands of visitors to our site
            </div>
          </div>
          <div class="col-md-3 motivation_box">
            <div class="include-where">&hellip; embedded in other sites</div>
            <!--
            <div class="include-where-graphic">
              <-%= image_tag 'about/widgets_adopters.png', size: "200x200" %>
            </div>
            -->
            <div class="include-where-text">
              <div style="text-align: left;">
                <p>By registering your event it will be:</p>
                <p>Listed on <%= TeSS::Config.site['title_short'] %></p>
                <p>Promoted on other sites that use our widgets</p>
                <p>Appear in more search results because of our search-engine optimisation</p>
              </div>
              Be seen across all the websites that display site resources through our <a href="developers#widgets">
              widgets</a>.
            </div>
          </div>
          <div class="col-md-3 motivation_box">
            <div class="include-where">&hellip; in search engines</div>
            <div class="include-where-graphic">
              <%= image_tag 'about/search_results.png', size: "200x100" %>
            </div>
            <div class="include-where-text">Be seen in search results more owing to our search-engine optimisation</div>
          </div>
        </div>
        <%== raw t 'register.methods' %>
      </div>

      <!-- AUTOMATIC REGISTRATION -->
      <div class="row">
        <div class="odd-about-block">
          <div id='automatic' class="h4">Automatic Registration</div>
          <p><%== raw t 'register.automatic' %></p>
          <!--
          <div class="row">
            <div class="col-md-3 motivation_box">
              <div class="register-condition-graphic"><i class="fa fa-ellipsis-h about-icons"></i></div>
              <div class="register-condition"><%== raw t 'register.auto_condition_1' %></div>
            </div>
            <div class="col-md-3 motivation_box">
              <div class="register-condition-graphic"><i class="fa fa-code about-icons"></i></div>
              <div class="register-condition"><%== raw t 'register.auto_condition_2' %></div>
            </div>
            <div class="col-md-3 motivation_box">
              <div class="register-condition-graphic"><i class="fa fa-flask about-icons"></i></div>
              <div class="register-condition"><%== raw t 'register.auto_condition_3' %></div>
            </div>
          </div>
          -->

          <!-- STRUCTURED DATA ->
          <div class="h5">Structured Data Types</div>
          <%== raw t 'register.structured' %>
          -->

          <!-- BIOSCHEMAS ->
          <div class="sub-about-block">
            <div id='bioschemas' class="h6">Schema.org / Bioschemas</div>
            <div class="row">
              <div class="col-lg-9">
                <%== raw t 'register.schema' %>
                <p>
                  <%== raw t 'register.bioschema_events' %>
                  <%== raw t 'register.bioschema_materials' %>
                </p>
                <hr>
                <b>Examples of sites using Bioschemas parsed by <%= TeSS::Config.site['title_short'] %></b>
                <div class="data-type-examples">
                  <%== raw t 'register.schema_example_1' %>
                  <%== raw t 'register.schema_example_2' %>
                  <%== raw t 'register.schema_example_3' %>
                </div>
              </div>
              <div class="col-lg-3">
                <%= image_tag 'about/bioschemas.png', class: "struct_data_type_logo" %>
                <%= image_tag 'about/schema-org-logo.png', class: "struct_data_type_logo" %>
              </div>
            </div>
          </div>
          -->

          <!-- API ->
          <div class="sub-about-block">
            <div id='api' class="h6">API</div>
            <div class="row">
              <div class="col-lg-9">
                <%== raw t 'register.api' %>
                <hr>
                <b>Examples of sites with APIs included in <%= TeSS::Config.site['title_short'] %></b>
                <div class="data-type-examples">
                  <%== raw t 'register.api_example_1' %>
                  <%== raw t 'register.api_example_2' %>
                  <%== raw t 'register.api_example_3' %>
                </div>
              </div>
              <div class="col-lg-3">
                <i class="fa fa-plug about-icons struct_data_type_logo"></i>
              </div>
            </div>
          </div>
          -->

          <!-- CALENDAR ->
          <div class="sub-about-block">
            <div id='calendar' class="h6">Calendar</div>
            <div class="row">
              <div class="col-lg-9">
                <%== raw t 'register.calendar' %>
                <hr>
                <b>Examples of calendar files parsed by <%= TeSS::Config.site['title_short'] %></b>
                <div class="data-type-examples">
                  <%== raw t 'register.calendar_example_1' %>
                  <%== raw t 'register.calendar_example_2' %>
                  <%== raw t 'register.calendar_example_3' %>
                </div>
              </div>
              <div class="col-lg-3">
                <i class="fa fa-calendar about-icons struct_data_type_logo"></i>
              </div>
            </div>
          </div>
          -->

          <!-- OTHER ->
          <div class="sub-about-block">
            <div id='other' class="h6">Other types</div>
            <%== raw t 'register.other_types' %>
          </div>
          -->

          <!--  CONTACT US ->
          <div class="sub-about-block">
            <%#= render :partial => "common/contact_form"%>
            <%== raw t 'register.advice' %>
          </div>
          -->

        </div>
      </div>


      <div class="row">
        <div class="even-about-block">
          <div id='manual' class="h4">Manual Registration</div>
          <%== raw t 'register.manual' %>
          <p>
            <%= link_to new_event_path, class: 'btn btn-primary', target: '_blank' do %>
              <i class="fa fa-plus-square"></i> Register event
            <% end %>
            <%= link_to new_material_path, class: 'btn btn-primary', target: '_blank' do %>
              <i class="fa fa-plus-square"></i> Register material
            <% end %>
          </p>
          <p>
            If you have resources that change frequently, we recommended that you establish an
            <a href="#automatic">automatic registration</a> solution.
          </p>
        </div>


        <!--
        <div id='include' class="h3">How TeSS works</div>
        <%= image_tag 'about/tess_architecture.png', class: "widgets_guide" %>
      </div>
      -->
      </div>
      <%= render :partial => 'links', :locals => { 'show': 'registering' } %>

    </div>
  </div>
</div>

app/views/about/tess.html.erb
<div class="wrapper">

  <% @feature_count = 0 %>

  <div id="sidebar" class="popout-sidebar">
    <%= render :partial => 'about_nav', locals: { show: 'home' } %>
  </div>

  <div id="content">
    <div class="about-block">
      <%= render :partial => 'links', :locals => { 'show': 'tess' } %>

      <div class="row">

        <div id='trainingregistry' class="h3">The <%== TeSS::Config.site['title'] %></div>
        <p><%== raw t 'about.registry' %></p>

        <!-- EVENTS-->

        <% if TeSS::Config.feature['events'] == true %>
          <div class="row <%= next_about_block(@feature_count += 1) %>">
            <div class="col-lg-2 about-resource-icon">
              <%= link_to events_path do %>
                <%= image_tag("dresa/Training_Default.png", height: "120px", alt: "Events") %>
                <p>Discover Events</p>
              <% end %>
            </div>
            <div class="col-lg-10 about-resource">
              <div id='events' class="h4">Events</div>
              <p><%== raw t 'about.events' %></p>
              <p>
                <%= TeSS::Config.site['title_short'] %> collects event information
                from <%= Event.all.collect { |x| x.content_provider_id }.uniq.count %>
                content providers, supplementing the data with geolocation information found using
                <%== raw t 'about.nominatim' %>.
              </p>
            </div>
          </div>
        <% end %>

        <!-- MATERIALS-->

        <% if TeSS::Config.feature['materials'] == true %>
          <div class="row <%= next_about_block(@feature_count += 1) %>">
            <div class="col-lg-2 about-resource-icon">
              <%= link_to materials_path do %>
                <%= image_tag("dresa/Training_Materials_Default.png", height: "120px", alt: "Events") %>
                <p>Discover Materials</p>
              <% end %>
            </div>

            <div class="col-lg-10 about-resource">
              <div id='materials' class="h4">Materials</div>
              <p><%== raw t 'about.materials' %></p>

              <p><%= TeSS::Config.site['title_short'] %> collects materials from
                <%= Material.all.collect { |x| x.content_provider_id }.uniq.count %>
                content providers.</p>
            </div>
          </div>
        <% end %>

        <!-- WORKFLOWS -->

        <% if TeSS::Config.feature['workflows'] == true %>
          <div class="row <%= next_about_block(@feature_count += 1) %>">
            <div class="row">
              <div class="col-lg-2 about-resource-icon">
                <%= link_to workflows_path do %>
                  <i class="fa fa-sitemap about-icons"></i><br>Discover Workflows
                <% end %>
              </div>

              <div class="col-lg-10 about-resource">
                <div id='workflows' class="h4">Training Workflows</div>
                <p><%== raw t 'about.workflows' %></p>
              </div>
            </div>

            <!-- INDIVIDUAL WORKFLOW TYPES-->
            <div class="sub-about-block">
              <div class="h5">Learning Paths</div>
              <p><%== raw t 'about.learning_paths' %></p>
            </div>

            <div class="sub-about-block">
              <div class="h5">Concept Maps</div>
              <p><%== raw t 'about.concept_maps' %></p>
            </div>

            <div class="sub-about-block">
              <div class="h5">Educational Resource</div>
              <p><%== raw t 'about.resources' %></p>
            </div>

          </div>
        <% end %>

        <!-- SUBSCRIBE-->

        <div class="row <%= next_about_block(@feature_count += 1) %>">
          <div class="row">
            <div class="col-lg-12">
              <div id='subscribe' class="h3">Subscribe</div>
              <p><%== raw t 'about.subscribe' %></p>
              <% if TeSS::Config.feature['subscription'] %>
                <p>The <%= link_to 'subscriptions manager', subscriptions_path %> page may be used to change the
                  frequency
                  of, or to remove, subscriptions.</p>
                <%= image_tag 'about/subscription.png', class: "widgets_guide" %>
              <% else %>
                <p>This feature is <strong>coming soon</strong> in the next phase of DReSA development.</p>
              <% end %>
            </div>
          </div>
        </div>

        <!-- WIDGET & API -->

        <div class="row <%= next_about_block(@feature_count += 1) %>">
          <div class="row">
            <div class="col-lg-12">
              <div id='widget' class="h3">Widgets & API</div>
              <p>To access <%= TeSS::Config.site['title_short'] %> data, <%== raw t 'about.widgets' %></p>
              <%= link_to 'Learn more about Widgets', developers_path(:anchor => "widgets"), class: 'btn btn-primary' %>
              <%= link_to 'Learn more about our API', developers_path(:anchor => "api"), class: 'btn btn-primary' %>
            </div>
          </div>
        </div>

      </div>

      <%= render :partial => 'links', :locals => { 'show': 'tess' } %>
    </div>
  </div>
</div>